export type Course = {
  slug: string;
  name: string;
  category: "Foundation" | "Diploma" | "Office & Accounts" | "Design & Media" | "Teacher Training" | "Abacus" | "Distance Education";
  duration: string;
  eligibility: string;
  summary: string;
  highlights: string[];
};

export const COURSES: Course[] = [
  {
    slug: "cit",
    name: "CIT — Certificate in Information Technology",
    category: "Foundation",
    duration: "3 Months",
    eligibility: "5th Std & Above",
    summary: "A beginner-friendly certificate course covering computer fundamentals, office tools, internet usage and digital confidence.",
    highlights: ["Computer Basics", "MS Office", "Internet & Email", "Certificate on Completion"],
  },
  {
    slug: "dit",
    name: "DIT — Diploma in Information Technology",
    category: "Diploma",
    duration: "6 Months",
    eligibility: "8th Std & Above",
    summary: "A practical diploma course for students who want a stronger base in IT, office applications and computer usage.",
    highlights: ["IT Fundamentals", "Office Applications", "Internet Skills", "Practical Training"],
  },
  {
    slug: "doa",
    name: "DOA — Diploma in Office Automation",
    category: "Office & Accounts",
    duration: "6 Months",
    eligibility: "SSLC & Above",
    summary: "Office-ready training for documentation, spreadsheets, presentations, email and daily computer-based office work.",
    highlights: ["MS Word", "MS Excel", "PowerPoint", "Office Workflow"],
  },
  {
    slug: "ddtp",
    name: "DDTP — Diploma in Desktop Publishing",
    category: "Design & Media",
    duration: "6 Months",
    eligibility: "SSLC",
    summary: "Design and print-focused course for students interested in layouts, posters, certificates, brochures and publishing work.",
    highlights: ["Page Layout", "Print Design", "Photo Editing", "Practical Projects"],
  },
  {
    slug: "dca",
    name: "DCA — Diploma in Computer Application",
    category: "Diploma",
    duration: "6 Months",
    eligibility: "SSLC",
    summary: "A popular computer application diploma covering office tools, internet, typing, basics of accounts and useful software skills.",
    highlights: ["MS Office", "Internet", "Typing", "Computer Applications"],
  },
  {
    slug: "deo",
    name: "DEO — Computer Data Entry Operator",
    category: "Office & Accounts",
    duration: "6 Months",
    eligibility: "SSLC / PUC",
    summary: "Focused training for data entry jobs with typing speed, accuracy, spreadsheets, forms and office data handling.",
    highlights: ["Typing Accuracy", "Data Entry Practice", "Excel Basics", "Office Records"],
  },
  {
    slug: "ddeo",
    name: "DDEO — Diploma in Computer Data Entry Operator",
    category: "Office & Accounts",
    duration: "1 Year",
    eligibility: "PUC / Degree",
    summary: "Advanced data entry and office operations course for students preparing for office, clerical and data-processing roles.",
    highlights: ["Advanced Typing", "Data Management", "Spreadsheets", "Office Documentation"],
  },
  {
    slug: "adit",
    name: "ADIT — Advance Diploma in Information Technology",
    category: "Diploma",
    duration: "1 Year",
    eligibility: "SSLC",
    summary: "A one-year advanced IT diploma designed to develop strong computer application and practical workplace skills.",
    highlights: ["Advanced IT Skills", "Office Suite", "Internet Tools", "Project Work"],
  },
  {
    slug: "pgdca",
    name: "PGDCA — Post Graduate Diploma in Computer Application",
    category: "Diploma",
    duration: "1 Year",
    eligibility: "Degree",
    summary: "A postgraduate diploma for graduates who want computer application knowledge for careers, higher studies and office roles.",
    highlights: ["Computer Applications", "Database Basics", "Programming Basics", "Career-Oriented Training"],
  },
  {
    slug: "pgdit",
    name: "PGDIT — Pre Graduate Diploma in Information Technology",
    category: "Diploma",
    duration: "1 Year",
    eligibility: "PUC",
    summary: "A one-year IT diploma for PUC students who want a strong foundation before degree or professional computer courses.",
    highlights: ["IT Foundation", "Office Tools", "Digital Skills", "Practical Assignments"],
  },
  {
    slug: "mtt",
    name: "MTT — Montessori Teacher Training (Computer Based)",
    category: "Teacher Training",
    duration: "1 Year",
    eligibility: "PUC",
    summary: "Computer-based Montessori teacher training for candidates who want to build a career in early childhood education.",
    highlights: ["Montessori Methods", "Child Development", "Computer-Based Learning", "Teaching Practice"],
  },
  {
    slug: "ntt",
    name: "NTT — Nursery Teacher Training (Computer Based)",
    category: "Teacher Training",
    duration: "1 Year",
    eligibility: "SSLC / PUC",
    summary: "Nursery teacher training with computer-supported learning methods and practical teaching preparation.",
    highlights: ["Nursery Teaching", "Child Psychology", "Learning Activities", "Teaching Practice"],
  },
  {
    slug: "dnttc",
    name: "DNTTC — Diploma in Nursery Teacher Training Course",
    category: "Teacher Training",
    duration: "1 Year",
    eligibility: "PUC & Above",
    summary: "Diploma course for nursery teacher training with classroom skills, activity planning and early learning methods.",
    highlights: ["Nursery Education", "Activity Planning", "Classroom Skills", "Practical Training"],
  },
  {
    slug: "ptt",
    name: "PTT — Primary Teacher Training",
    category: "Teacher Training",
    duration: "1 Year",
    eligibility: "PUC",
    summary: "Primary teacher training course focused on foundational teaching methods, classroom communication and student handling.",
    highlights: ["Primary Teaching", "Lesson Planning", "Classroom Management", "Teaching Methods"],
  },
  {
    slug: "dcttc",
    name: "DCTTC — Diploma in Computer Teacher Training Course",
    category: "Teacher Training",
    duration: "1 Year",
    eligibility: "PUC",
    summary: "Training course for candidates who want to teach computer subjects in schools, institutes or training centers.",
    highlights: ["Computer Teaching", "Lesson Delivery", "Practical Computer Lab", "Assessment Methods"],
  },
  {
    slug: "2d-3d-animation",
    name: "2D & 3D — Diploma in 2D & 3D Animation",
    category: "Design & Media",
    duration: "1 Year",
    eligibility: "PUC",
    summary: "Creative animation diploma covering 2D and 3D concepts, design basics and portfolio-oriented practical work.",
    highlights: ["2D Animation", "3D Basics", "Creative Design", "Portfolio Projects"],
  },
  {
    slug: "abacus-academy",
    name: "SNIT Abacus Academy",
    category: "Abacus",
    duration: "Weekend Batches",
    eligibility: "2nd Std to 7th Std",
    summary: "Abacus program for children to improve concentration, memory, mental maths speed and confidence.",
    highlights: ["Saturday 5:30 PM–7:00 PM", "Sunday 10:30 AM–12:30 PM", "Mental Maths", "Focus & Memory"],
  },
  {
    slug: "tally-gst",
    name: "Tally with GST",
    category: "Office & Accounts",
    duration: "Short Term",
    eligibility: "SSLC / PUC / Degree",
    summary: "Practical accounting course covering Tally, GST billing, ledgers, vouchers and business accounting basics.",
    highlights: ["Tally Prime", "GST Billing", "Ledgers & Vouchers", "Accounting Practice"],
  },
  {
    slug: "hardware",
    name: "Computer Hardware",
    category: "Foundation",
    duration: "Short Term",
    eligibility: "SSLC & Above",
    summary: "Hands-on computer hardware training covering PC parts, assembly, troubleshooting and maintenance basics.",
    highlights: ["PC Assembly", "Troubleshooting", "OS Installation", "Maintenance"],
  },
  {
    slug: "multimedia",
    name: "Multimedia",
    category: "Design & Media",
    duration: "Short Term",
    eligibility: "SSLC / PUC",
    summary: "Creative multimedia course covering graphic design, photo editing, basic animation and presentation skills.",
    highlights: ["Graphic Design", "Photo Editing", "Animation Basics", "Creative Projects"],
  },
];

export const CATEGORIES = Array.from(new Set(COURSES.map((c) => c.category)));
