// Auto-generated from real center photography. Do not hand-edit counts;
// regenerate via the image pipeline if photos change.

export type GalleryPhoto = {
  id: string;
  category: string;
  src: string;
  thumb: string;
  title: string;
  width: number;
  height: number;
};

export const GALLERY_PHOTOS: GalleryPhoto[] = [
  {
    id: "founder-01",
    category: "Founder",
    src: "/assets/images/founder-01.webp",
    thumb: "/assets/images/founder-01-thumb.webp",
    title: "Founder & Director 1",
    width: 1448,
    height: 1086,
  },
  {
    id: "founder-02",
    category: "Founder",
    src: "/assets/images/founder-02.webp",
    thumb: "/assets/images/founder-02-thumb.webp",
    title: "Founder & Director 2",
    width: 1229,
    height: 1536,
  },
  {
    id: "building-01",
    category: "Building",
    src: "/assets/images/building-01.webp",
    thumb: "/assets/images/building-01-thumb.webp",
    title: "SNIT Center Building 1",
    width: 1086,
    height: 1448,
  },
  {
    id: "building-02",
    category: "Building",
    src: "/assets/images/building-02.webp",
    thumb: "/assets/images/building-02-thumb.webp",
    title: "SNIT Center Building 2",
    width: 1448,
    height: 1086,
  },
  {
    id: "computer-lab-01",
    category: "Computer Lab",
    src: "/assets/images/computer-lab-01.webp",
    thumb: "/assets/images/computer-lab-01-thumb.webp",
    title: "Computer Lab — Practical Training 1",
    width: 1600,
    height: 1200,
  },
  {
    id: "computer-lab-02",
    category: "Computer Lab",
    src: "/assets/images/computer-lab-02.webp",
    thumb: "/assets/images/computer-lab-02-thumb.webp",
    title: "Computer Lab — Practical Training 2",
    width: 1600,
    height: 1204,
  },
  {
    id: "computer-lab-03",
    category: "Computer Lab",
    src: "/assets/images/computer-lab-03.webp",
    thumb: "/assets/images/computer-lab-03-thumb.webp",
    title: "Computer Lab — Practical Training 3",
    width: 1600,
    height: 1200,
  },
  {
    id: "computer-lab-04",
    category: "Computer Lab",
    src: "/assets/images/computer-lab-04.webp",
    thumb: "/assets/images/computer-lab-04-thumb.webp",
    title: "Computer Lab — Practical Training 4",
    width: 1600,
    height: 1204,
  },
  {
    id: "computer-lab-05",
    category: "Computer Lab",
    src: "/assets/images/computer-lab-05.webp",
    thumb: "/assets/images/computer-lab-05-thumb.webp",
    title: "Computer Lab — Practical Training 5",
    width: 1600,
    height: 1204,
  },
  {
    id: "computer-lab-06",
    category: "Computer Lab",
    src: "/assets/images/computer-lab-06.webp",
    thumb: "/assets/images/computer-lab-06-thumb.webp",
    title: "Computer Lab — Practical Training 6",
    width: 1600,
    height: 1204,
  },
  {
    id: "computer-lab-07",
    category: "Computer Lab",
    src: "/assets/images/computer-lab-07.webp",
    thumb: "/assets/images/computer-lab-07-thumb.webp",
    title: "Computer Lab — Practical Training 7",
    width: 1600,
    height: 1204,
  },
  {
    id: "computer-lab-08",
    category: "Computer Lab",
    src: "/assets/images/computer-lab-08.webp",
    thumb: "/assets/images/computer-lab-08-thumb.webp",
    title: "Computer Lab — Practical Training 8",
    width: 1600,
    height: 1200,
  },
  {
    id: "classroom-01",
    category: "Classroom",
    src: "/assets/images/classroom-01.webp",
    thumb: "/assets/images/classroom-01-thumb.webp",
    title: "Classroom Training Session 1",
    width: 1600,
    height: 1200,
  },
  {
    id: "classroom-02",
    category: "Classroom",
    src: "/assets/images/classroom-02.webp",
    thumb: "/assets/images/classroom-02-thumb.webp",
    title: "Classroom Training Session 2",
    width: 1600,
    height: 1204,
  },
  {
    id: "students-01",
    category: "Students",
    src: "/assets/images/students-01.webp",
    thumb: "/assets/images/students-01-thumb.webp",
    title: "Students at SNIT 1",
    width: 1204,
    height: 1600,
  },
  {
    id: "students-02",
    category: "Students",
    src: "/assets/images/students-02.webp",
    thumb: "/assets/images/students-02-thumb.webp",
    title: "Students at SNIT 2",
    width: 1204,
    height: 1600,
  },
  {
    id: "students-03",
    category: "Students",
    src: "/assets/images/students-03.webp",
    thumb: "/assets/images/students-03-thumb.webp",
    title: "Students at SNIT 3",
    width: 1200,
    height: 1600,
  },
  {
    id: "students-04",
    category: "Students",
    src: "/assets/images/students-04.webp",
    thumb: "/assets/images/students-04-thumb.webp",
    title: "Students at SNIT 4",
    width: 1204,
    height: 1600,
  },
  {
    id: "students-05",
    category: "Students",
    src: "/assets/images/students-05.webp",
    thumb: "/assets/images/students-05-thumb.webp",
    title: "Students at SNIT 5",
    width: 1200,
    height: 1600,
  },
  {
    id: "students-06",
    category: "Students",
    src: "/assets/images/students-06.webp",
    thumb: "/assets/images/students-06-thumb.webp",
    title: "Students at SNIT 6",
    width: 1204,
    height: 1600,
  },
  {
    id: "students-07",
    category: "Students",
    src: "/assets/images/students-07.webp",
    thumb: "/assets/images/students-07-thumb.webp",
    title: "Students at SNIT 7",
    width: 1200,
    height: 1600,
  },
  {
    id: "abacus-01",
    category: "Abacus",
    src: "/assets/images/abacus-01.webp",
    thumb: "/assets/images/abacus-01-thumb.webp",
    title: "Abacus Academy Session 1",
    width: 1516,
    height: 1010,
  },
  {
    id: "abacus-02",
    category: "Abacus",
    src: "/assets/images/abacus-02.webp",
    thumb: "/assets/images/abacus-02-thumb.webp",
    title: "Abacus Academy Session 2",
    width: 1600,
    height: 1194,
  },
  {
    id: "abacus-03",
    category: "Abacus",
    src: "/assets/images/abacus-03.webp",
    thumb: "/assets/images/abacus-03-thumb.webp",
    title: "Abacus Academy Session 3",
    width: 1600,
    height: 1200,
  },
  {
    id: "abacus-04",
    category: "Abacus",
    src: "/assets/images/abacus-04.webp",
    thumb: "/assets/images/abacus-04-thumb.webp",
    title: "Abacus Academy Session 4",
    width: 1600,
    height: 1200,
  },
  {
    id: "events-01",
    category: "Events",
    src: "/assets/images/events-01.webp",
    thumb: "/assets/images/events-01-thumb.webp",
    title: "SNIT Event 1",
    width: 1600,
    height: 1200,
  },
  {
    id: "events-02",
    category: "Events",
    src: "/assets/images/events-02.webp",
    thumb: "/assets/images/events-02-thumb.webp",
    title: "SNIT Event 2",
    width: 1600,
    height: 1200,
  },
  {
    id: "events-03",
    category: "Events",
    src: "/assets/images/events-03.webp",
    thumb: "/assets/images/events-03-thumb.webp",
    title: "SNIT Event 3",
    width: 1600,
    height: 1200,
  },
  {
    id: "events-04",
    category: "Events",
    src: "/assets/images/events-04.webp",
    thumb: "/assets/images/events-04-thumb.webp",
    title: "SNIT Event 4",
    width: 1600,
    height: 1200,
  },
  {
    id: "events-05",
    category: "Events",
    src: "/assets/images/events-05.webp",
    thumb: "/assets/images/events-05-thumb.webp",
    title: "SNIT Event 5",
    width: 1600,
    height: 1200,
  },
  {
    id: "events-06",
    category: "Events",
    src: "/assets/images/events-06.webp",
    thumb: "/assets/images/events-06-thumb.webp",
    title: "SNIT Event 6",
    width: 1600,
    height: 1200,
  },
  {
    id: "events-07",
    category: "Events",
    src: "/assets/images/events-07.webp",
    thumb: "/assets/images/events-07-thumb.webp",
    title: "SNIT Event 7",
    width: 1600,
    height: 1200,
  },
  {
    id: "events-08",
    category: "Events",
    src: "/assets/images/events-08.webp",
    thumb: "/assets/images/events-08-thumb.webp",
    title: "SNIT Event 8",
    width: 1600,
    height: 1200,
  },
  {
    id: "certificates-01",
    category: "Certificates",
    src: "/assets/images/certificates-01.webp",
    thumb: "/assets/images/certificates-01-thumb.webp",
    title: "Certificate Distribution 1",
    width: 1600,
    height: 1265,
  },
  {
    id: "certificates-02",
    category: "Certificates",
    src: "/assets/images/certificates-02.webp",
    thumb: "/assets/images/certificates-02-thumb.webp",
    title: "Certificate Distribution 2",
    width: 1600,
    height: 1200,
  },
  {
    id: "gallery-01",
    category: "Gallery",
    src: "/assets/images/gallery-01.webp",
    thumb: "/assets/images/gallery-01-thumb.webp",
    title: "Life at SNIT 1",
    width: 1600,
    height: 1200,
  },
  {
    id: "gallery-02",
    category: "Gallery",
    src: "/assets/images/gallery-02.webp",
    thumb: "/assets/images/gallery-02-thumb.webp",
    title: "Life at SNIT 2",
    width: 1200,
    height: 1600,
  },
  {
    id: "gallery-03",
    category: "Gallery",
    src: "/assets/images/gallery-03.webp",
    thumb: "/assets/images/gallery-03-thumb.webp",
    title: "Life at SNIT 3",
    width: 1200,
    height: 1600,
  },
  {
    id: "gallery-04",
    category: "Gallery",
    src: "/assets/images/gallery-04.webp",
    thumb: "/assets/images/gallery-04-thumb.webp",
    title: "Life at SNIT 4",
    width: 1200,
    height: 1600,
  },
  {
    id: "gallery-05",
    category: "Gallery",
    src: "/assets/images/gallery-05.webp",
    thumb: "/assets/images/gallery-05-thumb.webp",
    title: "Life at SNIT 5",
    width: 1200,
    height: 1600,
  },
  {
    id: "gallery-06",
    category: "Gallery",
    src: "/assets/images/gallery-06.webp",
    thumb: "/assets/images/gallery-06-thumb.webp",
    title: "Life at SNIT 6",
    width: 1200,
    height: 1600,
  },
  {
    id: "gallery-07",
    category: "Gallery",
    src: "/assets/images/gallery-07.webp",
    thumb: "/assets/images/gallery-07-thumb.webp",
    title: "Life at SNIT 7",
    width: 1599,
    height: 899,
  },
  {
    id: "gallery-08",
    category: "Gallery",
    src: "/assets/images/gallery-08.webp",
    thumb: "/assets/images/gallery-08-thumb.webp",
    title: "Life at SNIT 8",
    width: 1600,
    height: 1204,
  },
];

export const GALLERY_CATEGORIES = Array.from(new Set(GALLERY_PHOTOS.map((p) => p.category)));
